### ISSUE TITLE
Allow user to specify build directory 

### ISSUE THREAD

**Issue by leezu** [sakaki-/buildkernel#12]
First thanks for creating this script and the guide!

As far as I see the buildkernel script builds the kernel in the LINUXDIR="/usr/src/linux" directory, which in case of newer devices is often located on a SSD. It would be nice to allow the user to optionally specify a builddirectory to which the contents of /usr/src/linux are then copied and in which the compilation is subsequently performed.

This would allow to specify a directory on a tmpfs and thereby to work around unnecessary stressing of the SSD.

**Comment by sakaki-** [comment]
Sounds sensible - if you submit a PR to that effect I will test and merge it.

**Comment by leezu** [comment]
I created a PR. Please let me know what you think about it. Suggestions for improvement welcome ;)
