### ISSUE TITLE
sys-kernel/buildkernel-1.0.23 SYSTEMD_INIT FIX

### ISSUE THREAD

**Issue by frunzales** [sakaki-/buildkernel#15]
Bug: https://bugs.gentoo.org/625462

### Description
As of systemd-234-r2, /usr/lib/systemd/systemd is a symlink to /lib/systemd/systemd; As a consequence, the SYSTEMD_INIT variable in buildkernel:59 should be adjusted accordingly.

### Note
It looks like starting with systemd-235 the symlinks implemented in sys-apps/systemd-234-r2 will be deprecated.

**Comment by sakaki-** [comment]
Ack. Good spot, will fix this.

**Comment by leezu** [comment]
Hm, this causes a failed boot when using systemd 233-r4. Note that systemd-234-r2 is not yet in stable. Can you create some warning for users if they upgrade to the new buildkernel release? Not sure how that could be done, maybe `eselect news`?

**Comment by leezu** [comment]
Or, as there are still symlinks in systemd-234-r2 you may rely on the symlinks until systemd-234-r2 moves to stable (assuming/hoping that this would happen before systemd-235 is released). Not sure though if you are targeting stable users at all with buildkernel?

**Comment by sakaki-** [comment]
Thanks I _should_ have tested this on stable as well ><. I'm definitely targeting users on `amd64` (for my EFI install guide on the Gentoo wiki).
Temporarily reverted the `SYSTEMD_INIT` change (until stable systemd reflects it) and released 1.0.25.

**Comment by sakaki-** [comment]
Reopening as reverted until stable tracks.

**Comment by leezu** [comment]
No worries. Maybe this issue should be raised with systemd maintainers, so that they make sure symlinks are provided in testing until the new layout is also present in stable?
