### ISSUE TITLE
Self Breaking Plymouth

### ISSUE THREAD

**Issue by nileshp87** [sakaki-/buildkernel#2]
I've been following your guide on the gentoo wiki on secure book, and found this tool. 

I ran into an issue with the script where whenever the system booted up with plymouth it would immediately crash out due to an error from lvmetad. It seems the kernel is trying to grab the lvm disks before they are decrypted. After quite a bit of digging through the various problems, I have come to find that the issue exists in the script. 

On my laptop the simplest fix is omitting the dolvm flag from the kernel parameters, and it magicall fixes it. I'd submit a PR for the fix but if someone could repro this first that'd be handy.
 
Thanks a lot for the guide by the way, it's actually easier to follow than the official handbook.

**Comment by sakaki-** [comment]
Thanks for the bug report. I'll look into this issue this weekend. Best, sakaki

**Comment by sakaki-** [comment]
I have tried removing the `dolvm` flag but it breaks the boot on one of my ASUS laptops (with `plymouth` enabled, `amd64`), as `genkernel-next`'s init script (which is what consumes the `dolvm` flag; see e.g. [here](https://github.com/Sabayon/genkernel-next/search?utf8=%E2%9C%93&q=USE_LVM_NORMAL)) cannot find the root volume anymore. Are you running `amd64` or `~amd64`?

**Comment by sakaki-** [comment]
Closing as no response for over a month
