### ISSUE TITLE
KERNEL_CMD_LINE quoting issue

### ISSUE THREAD

**Issue by leezu** [sakaki-/buildkernel#21]
Recently `set_kernel_config "CMDLINE" "\"${KERNEL_CMD_LINE}\""` (https://github.com/sakaki-/buildkernel/blob/master/buildkernel#L1671) started causing the following error:

```
* Setting kernel command line = 'root=/dev/ram0 crypt_root=/dev/disk/by-partuuid/9e5664ef-8698-46dd-8553-8faac7d3ad62 dolvm real_root=/dev/mapper/vg1-root rootfstype=btrfs
btrfs
btrfs real_init=/lib/systemd/systemd real_resume=/dev/mapper/vg1-swap keymap=us quiet splash udev.log-priority=3 root_trim=yes elevator=bfq kvm_intel.nested=1'...
sed: -e expression #1, char 216: unterminated `s' command
```

For some reason `"\"${KERNEL_CMD_LINE}\""` caused insertion of newlines, that render the sed expression invalid.

I am not sure why the issue started occurring now and not previously.

**Comment by sakaki-** [comment]
I think the issue may be stemming from [this recently introduced change](https://github.com/sakaki-/buildkernel/blame/master/buildkernel#L480-L484); look at the repeated `btrfs` entries in your kernel command line. Perhaps it is the case that `findmnt` is returning multiple entries on your system, _pace_ [this comment](https://github.com/sakaki-/buildkernel/pull/20#issuecomment-422841828)?

Could you please post the output on your system of:
```console
# /bin/findmnt -n -o FSTYPE /dev/mapper/vg1-root
```

Thanks for reporting!

**Comment by leezu** [comment]
Thanks for your prompt reply @sakaki- . Indeed findmnt returns multiple entries:

```
% /bin/findmnt -n -o FSTYPE /dev/mapper/vg1-root                                                                             ~
btrfs
btrfs
btrfs
```

**Comment by leezu** [comment]
Sure:

```
/             /dev/mapper/vg1-root[/@]     btrfs  rw,noatime,ssd,discard,space_cache,subvolid=258,subvol=/@
/mnt/vg1-root /dev/mapper/vg1-root         btrfs  rw,noatime,ssd,discard,space_cache,subvolid=5,subvol=/
/home         /dev/mapper/vg1-root[/@home] btrfs  rw,noatime,ssd,discard,space_cache,subvolid=257,subvol=/@home

```
Context:

> A Btrfs subvolume is an independently mountable POSIX filetree and not a block device (and cannot be treated as one). Most other POSIX filesystems have a single mountable root, Btrfs has an independent mountable root for the volume (top level subvolume) and for each subvolume; a Btrfs volume can contain more than a single filetree, it can contain a forest of filetrees. A Btrfs subvolume can be thought of as a POSIX file namespace. 

https://btrfs.wiki.kernel.org/index.php/SysadminGuide#Subvolumes

**Comment by sakaki-** [comment]
Hmm, I see (must admit this is one FS I haven't used so far). So would it be safe to assume all of the subvolumes also have FSTYPE `btrfs` then?

**Comment by leezu** [comment]
Yes, all subvolumes are part of the single btrfs filesystem. So for the case of btrfs just taking the first output of findnmt should be safe.

**Comment by sakaki-** [comment]
Perfect. OK, I'll add a fix for this issue now and re-release. Thanks for bringing it to my attention ^-^
