### ISSUE TITLE
mount second disk at boot?

### ISSUE THREAD

**Issue by LIII-XXII** [sakaki-/buildkernel#27]
Hi Sakaki, thanks for your continued support of this tool.

Is it possible to mount more than a volume at boot time with the same key (or with a different one, though as they would both be on the same USB key, it wouldn't really bring much to do so) without having to copy the key somewhere on the machine?
I have looked around and saw some tips about /etc/fstab and /etc/crypttab but no cmdline options to do that. How would one get around to that?
Specifically I am thinking of moving /home to a separate disk.

**Comment by sakaki-** [comment]
If you are using `systemd` the easiest way to move `/home` is just to do the `/etc/crypttab` thing, which I cover in my mini-guide [here](https://wiki.gentoo.org/wiki/Sakaki%27s_EFI_Install_Guide/Extending_LUKS_to_Protect_an_Additional_Drive).

The use case for multi-volume unlock at boot is usually to support some form of RAID; this is not currently supported as part of `buildkernel` but has been requested a few times and I will probably look at adding it some time in the future.

Best, sakaki

**Comment by LIII-XXII** [comment]
thanks. I guess this is indeed the best solution, so I will move /home to the second disk and grow the root partition.

**Comment by LIII-XXII** [comment]
update: I was able to do it following the mini-guide, thanks again.
