### ISSUE TITLE
efibootmgr failes for nvme devices

### ISSUE THREAD

**Issue by danielmorlock** [sakaki-/buildkernel#3]
This won't work for nvme device nodes (i.e. /dev/nvme0n1p1): https://github.com/sakaki-/buildkernel/blob/master/buildkernel#L1396

**Comment by sakaki-** [comment]
Ah, OK. I'll have a look at fixing this in the next few days.

**Comment by danielmorlock** [comment]
There is also an issue with efibootmgr itself failing to add nvme devices: https://github.com/rhinstaller/efibootmgr/issues/4

**Comment by sakaki-** [comment]
I've made a small change to `buildkernel` that'll hopefully at least pass the right args to `efibootmgr` for nvme paths; but I haven't released an ebuild for it in `sakaki-tools` yet. Anyway, if you download `buildkernel` directly from this repo (it's just a script) and run it, you can test whether or not this works (I have no nvme devices on any of my own systems yet). If it does, I can bump the ebuild also.

Of course if `efibootmgr` itself is also also broken, this fix isn't going to help you a lot ><

**Comment by sakaki-** [comment]
Assuming commit f8428d6 has fixed this issue; closing.
