### ISSUE TITLE
Depends on sys-kernel/installkernel-gentoo

### ISSUE THREAD

**Issue by tecknicaltom** [sakaki-/buildkernel#34]
sys-apps/debianutils recently moved installkernel to an external ebuild (2 actually, but I have not tried sys-kernel/installkernel-systemd-boot because I use OpenRC) behind the installkernel USE flag. Without this package installed, the make install at https://github.com/sakaki-/buildkernel/blob/master/buildkernel#L1953 uses the default install script which does not include the version in the resulting filenames. This results in a failure in check_if_enough_disk_space_for_backups

**Comment by sakaki-** [comment]
Thanks for reporting!
Closed by https://github.com/sakaki-/sakaki-tools/commit/ac4852fe85b8bd495c956d18c812c4eb9c65a2eb
Best, sakaki
