### ISSUE TITLE
genkernel bypasses genkernel.conf options

### ISSUE THREAD

**Issue by BlueDragonX** [sakaki-/buildkernel#4]
As the title says, buildkernel hardcodes some commandline options to genkernel that are better left as options to the user. These are specifically `--firmware` and `--all-ramdisk-modules`. The first is especially egregious when there is limited disk space to work with in `/boot`.

I'm testing a patch for this right now and will submit a PR if successful.

**Comment by sakaki-** [comment]
OK thanks, I'll test & merge this when you send it through. Best, sakaki

**Comment by sakaki-** [comment]
Thanks for the PR. Only thing is, that some existing users will be relying on the firmware being present in early boot for graphics drivers etc., so I'd be reluctant to just delete the flag outright. One other approach I've been thinking of for a while, would be to have a `/etc/buildkernel.conf` file, and have a variable in there specifying which (if any) flags to pass to `genkernel`. It would then be a simple case to modify this (or comment it out) if desired. And there are a number of other items that could also be placed into such a config file, if it existed.
If I implemented that, would it address your use case?

**Comment by BlueDragonX** [comment]
It would, though that seems like a lot of extra work to accomplish the same
thing. I rely on firmware as well, the difference is I specify which files
in genkernel.conf. That's pretty standard so I would expect users to know
about it. You do mention configuring genkernel in the guide, so being more
explicit about the firmware piece would be an improvement.

**Comment by sakaki-** [comment]
Hi - I've released a new version of buildkernel (1.0.17) with the variable  `ADDITIONALGENKERNELOPTS`. This is set, by default, to `"--all-ramdisk-modules --firmware"`, but if you wish to prevent the modules and firmware being forcibly added, simply place
```
ADDITIONALGENKERNELOPTS=""
```
into the file `/etc/buildkernel.conf`.
Let me know if this addresses your issue. I will look to reflect the point in the install guide also.
Best, sakaki

**Comment by sakaki-** [comment]
This fix has been live for a while now - closing.
