### ISSUE TITLE
Small patch for disabling of creating/changing new efi boot parameters

### ISSUE THREAD

**Issue by gizahNL** [sakaki-/buildkernel#7]
Use case: when using a EFI bootloader (for example reFind) it is not required nor advisable to change the efi boot parameters. I made a small, perhaps not very efficient change:

```
50,51d49
< DEFAULTCREATEEFIBOOT=1
< CREATEEFIBOOT="${DEFAULTCREATEEFIBOOT}"
1391,1395c1389
<     if	((CREATEEFIBOOT==1)); then
<     		declare -i NEWBOOTENTRYNEEDED=1
< 	else
< 		declare -i NEWBOOTENTRYNEEDED=0
<     fi
---
>     declare -i NEWBOOTENTRYNEEDED=1

```

**Comment by sakaki-** [comment]
Would this be better as a command line parameter or a variable sourced from /etc/buildkernel.conf?

**Comment by gizahNL** [comment]
with this specifying CREATEEFIBOOT=0 in the .conf file it works, without specification in file it should work as default.

I would say storing it in .conf file is the best way: less typing.

I don't think an extra option in the interactive setup mode is needed, I would consider it a function a bit more advanced that would only be used by people that already know of efi bootloaders, though perhaps a mention in the wiki article or conf file describing the option would be nice for other users ;)

Personally I love reFind since it foregoes of having to manually choose the boot from the bios, also if the bios is setup to fully probe usb devices and reFind configured to probe external devices it will show the usb as a bootable device.

**Comment by sakaki-** [comment]
OK. Submit as a PR and I will test & merge it, that way you'll get credited on the `buildkernel` git history. In an ideal world your PR would also have a commit for `buildkernel.conf.5` (add to the end of "the following variables are optional" section). I'll add something to the wiki article when I next do an update (within a few weeks, certainly).

If `CREATEEFIBOOT` and `DEFAULTCREATEEFIBOOT` are to be valued 1/0 you might want to `declare -i` them.

**Comment by gizahNL** [comment]
I'll make some time for it in the weekend :) 

Thanks btw for the indepth wiki, great scripts and quick response! :)

**Comment by sakaki-** [comment]
Closing (please re-open if your testing of the fix reveals any issues). Thanks, sakaki
