### ISSUE TITLE
script should check for vfat as module

### ISSUE THREAD

**Issue by gizahNL** [sakaki-/buildkernel#8]
I found out that having vfat compiled in as a module breaks the automated booting (automated mount failed, 'mount -t vfat PARTUUID=etcetc' on ramdisk commandline worked), the script should either force compiling into kernel or perhaps load the module/give extended mount command before trying to mount the USB key.

**Comment by sakaki-** [comment]
Closing (please re-open if your testing of the fix reveals any issues). Thanks, sakaki
